// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notely.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Notely.Data.Migrations
{
    [DbContext(typeof(NotelyDbContext))]
    partial class NotelyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Notely.Entities.Chapitre", b =>
                {
                    b.Property<int>("IdChapitre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cha_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdChapitre"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("cha_date");

                    b.Property<string>("Difficulte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cha_difficulte");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cha_etat");

                    b.Property<int>("IdCours")
                        .HasColumnType("integer")
                        .HasColumnName("cou_id");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cha_libelle");

                    b.HasKey("IdChapitre");

                    b.HasIndex("IdCours");

                    b.ToTable("t_e_chapitre_cha", "public");
                });

            modelBuilder.Entity("Notely.Entities.Compte", b =>
                {
                    b.Property<int>("IdCompte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCompte"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("com_date_creation");

                    b.Property<DateTime?>("DateDerniereConnexion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("com_date_derniere_connexion");

                    b.Property<bool>("DoitChangerMotDePasse")
                        .HasColumnType("boolean")
                        .HasColumnName("com_doit_changer_mdp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("com_email");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("com_mdp_hash");

                    b.HasKey("IdCompte");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("t_e_compte_com", "public");
                });

            modelBuilder.Entity("Notely.Entities.Cours", b =>
                {
                    b.Property<int>("IdCours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cou_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCours"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cou_date_creation");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cou_nom");

                    b.HasKey("IdCours");

                    b.HasIndex("IdCompte");

                    b.ToTable("t_e_cours_cou", "public");
                });

            modelBuilder.Entity("Notely.Entities.Evenement", b =>
                {
                    b.Property<int>("IdEvenement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("evt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvenement"));

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("evt_commentaire");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("evt_couleur");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("evt_date");

                    b.Property<TimeOnly>("HeureDebut")
                        .HasColumnType("time without time zone")
                        .HasColumnName("evt_heure_debut");

                    b.Property<TimeOnly>("HeureFin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("evt_heure_fin");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("evt_titre");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("evt_type");

                    b.HasKey("IdEvenement");

                    b.HasIndex("IdCompte");

                    b.ToTable("t_e_evenement_evt", "public");
                });

            modelBuilder.Entity("Notely.Entities.ExerciceSeance", b =>
                {
                    b.Property<int>("IdExerciceSeance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("exs_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdExerciceSeance"));

                    b.Property<int>("IdSeance")
                        .HasColumnType("integer")
                        .HasColumnName("sea_id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("exs_nom");

                    b.HasKey("IdExerciceSeance");

                    b.HasIndex("IdSeance");

                    b.ToTable("t_e_exercice_seance_exs", "public");
                });

            modelBuilder.Entity("Notely.Entities.Note", b =>
                {
                    b.Property<int>("IdNote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("not_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNote"));

                    b.Property<bool>("Fait")
                        .HasColumnType("boolean")
                        .HasColumnName("not_fait");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("not_texte");

                    b.HasKey("IdNote");

                    b.HasIndex("IdCompte");

                    b.ToTable("t_e_note_not", "public");
                });

            modelBuilder.Entity("Notely.Entities.Seance", b =>
                {
                    b.Property<int>("IdSeance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sea_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeance"));

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sea_commentaire");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("sea_date");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.HasKey("IdSeance");

                    b.HasIndex("IdCompte");

                    b.ToTable("t_e_seance_sea", "public");
                });

            modelBuilder.Entity("Notely.Entities.Serie", b =>
                {
                    b.Property<int>("IdSerie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ser_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSerie"));

                    b.Property<int>("IdExerciceSeance")
                        .HasColumnType("integer")
                        .HasColumnName("exs_id");

                    b.Property<int>("NombreReps")
                        .HasColumnType("integer")
                        .HasColumnName("ser_reps");

                    b.Property<int>("NumeroSerie")
                        .HasColumnType("integer")
                        .HasColumnName("ser_numero");

                    b.Property<decimal?>("Poids")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("ser_poids");

                    b.HasKey("IdSerie");

                    b.HasIndex("IdExerciceSeance");

                    b.ToTable("t_e_serie_ser", "public");
                });

            modelBuilder.Entity("Notely.Entities.Todo", b =>
                {
                    b.Property<int>("IdTodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tod_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTodo"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("tod_date");

                    b.Property<bool>("Fait")
                        .HasColumnType("boolean")
                        .HasColumnName("tod_fait");

                    b.Property<int>("IdCompte")
                        .HasColumnType("integer")
                        .HasColumnName("com_id");

                    b.Property<int>("IdCours")
                        .HasColumnType("integer")
                        .HasColumnName("cou_id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tod_nom");

                    b.HasKey("IdTodo");

                    b.HasIndex("IdCompte");

                    b.HasIndex("IdCours");

                    b.ToTable("t_e_todo_tod", "public");
                });

            modelBuilder.Entity("Notely.Entities.Chapitre", b =>
                {
                    b.HasOne("Notely.Entities.Cours", "CoursNav")
                        .WithMany("Chapitres")
                        .HasForeignKey("IdCours")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoursNav");
                });

            modelBuilder.Entity("Notely.Entities.Cours", b =>
                {
                    b.HasOne("Notely.Entities.Compte", "CompteNav")
                        .WithMany("Cours")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteNav");
                });

            modelBuilder.Entity("Notely.Entities.Evenement", b =>
                {
                    b.HasOne("Notely.Entities.Compte", "CompteNav")
                        .WithMany("Evenements")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteNav");
                });

            modelBuilder.Entity("Notely.Entities.ExerciceSeance", b =>
                {
                    b.HasOne("Notely.Entities.Seance", "SeanceNav")
                        .WithMany("ExercicesSeance")
                        .HasForeignKey("IdSeance")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeanceNav");
                });

            modelBuilder.Entity("Notely.Entities.Note", b =>
                {
                    b.HasOne("Notely.Entities.Compte", "CompteNav")
                        .WithMany("Notes")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteNav");
                });

            modelBuilder.Entity("Notely.Entities.Seance", b =>
                {
                    b.HasOne("Notely.Entities.Compte", "CompteNav")
                        .WithMany("Seances")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteNav");
                });

            modelBuilder.Entity("Notely.Entities.Serie", b =>
                {
                    b.HasOne("Notely.Entities.ExerciceSeance", "ExerciceSeanceNav")
                        .WithMany("Series")
                        .HasForeignKey("IdExerciceSeance")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciceSeanceNav");
                });

            modelBuilder.Entity("Notely.Entities.Todo", b =>
                {
                    b.HasOne("Notely.Entities.Compte", "CompteNav")
                        .WithMany("Todos")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Notely.Entities.Cours", "CoursNav")
                        .WithMany("Todos")
                        .HasForeignKey("IdCours")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteNav");

                    b.Navigation("CoursNav");
                });

            modelBuilder.Entity("Notely.Entities.Compte", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Evenements");

                    b.Navigation("Notes");

                    b.Navigation("Seances");

                    b.Navigation("Todos");
                });

            modelBuilder.Entity("Notely.Entities.Cours", b =>
                {
                    b.Navigation("Chapitres");

                    b.Navigation("Todos");
                });

            modelBuilder.Entity("Notely.Entities.ExerciceSeance", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("Notely.Entities.Seance", b =>
                {
                    b.Navigation("ExercicesSeance");
                });
#pragma warning restore 612, 618
        }
    }
}
